[programs.devnet]
messitributesolanacontract = "Bs4SdFvqvYv2zndzEhNDdi1BUc9ffVjuNKpfy8Pf3P2a"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/sebitokazu/.config/solana/id.json"

[scripts]
test = "node tests/messitributesolanacontract.js"
